#!/usr/bin/env python3
"""Finite audio/motion review of the actual encoded promo through OpenRouter."""
import argparse
import base64
import hashlib
import json
import subprocess
from pathlib import Path
from generate import budget,request,receipt

ROOT=Path(__file__).resolve().parents[2]

def main():
    p=argparse.ArgumentParser();p.add_argument('--video',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--action',default='final-av-review');p.add_argument('--model',default='google/gemini-3.8-flash');p.add_argument('--reasoning-effort',choices=['low','medium','high']);a=p.parse_args()
    out=a.output.resolve();video=a.video.resolve();proxy=out/'critic-proxy.mp4';video_sha=hashlib.sha256(video.read_bytes()).hexdigest()
    brief_path=out/'production-brief.json'
    brief=json.loads((brief_path if brief_path.exists() else ROOT/'tools/promo/brief.json').read_text())
    serial=['-threads','1'] if brief.get('revision')=='v5' else []
    subprocess.run(['ffmpeg','-v','error','-y',*serial,'-i',str(video),'-vf','scale=1280:720','-c:v','libx264','-crf','26','-preset','fast',*serial,'-c:a','aac','-b:a','128k',str(proxy)],check=True)
    script=brief['narration']
    prompt='''Review this actual sixty-second game promo, including its AUDIO and MOTION, not just text. This edit was authored by the requesting assistant in the same session. Give concise evidence with timecodes. Check narration completeness, pronunciation of Dynamix (DYE-nuh-micks), intelligibility and energy, sentence-splice consistency, music balance, unexpected vocals, the short crew call near 32 seconds (quote what you actually hear), tank anatomy/continuity/flicker, transitions, frame clipping, readable subtitles, complete 4:3 game display, and the endcard including original PC game requirement and David Ming Kenny dedication. In particular, is any extra word actually spoken between crew voices and bring? Screens show genuine original-game packet recordings in EGA and Godot presentation; cinematic tank shots are illustrative sequences. Do not assume they are gameplay. Do not infer source rights or claim mathematical loudness measurements. Return a JSON object with audio_accessible, video_accessible, verdict (pass or repair), narration_issues, crew_call_heard, motion_issues, caption_issues, endcard_issues, and delivery_assessment. Issues should include time and direct observable evidence. Mark uncertainty rather than inventing defects. Approved spoken narration follows:\n'''+script
    if brief.get('revision')=='v2':
        crew=brief['crew_showcase']
        prompt=f'''Review the actual {brief['duration_seconds']}-second revised game promo, including audio and motion. The requesting assistant authored this edit in this session. Return concise JSON with audio_accessible, video_accessible, verdict (pass or repair), narration_issues, crew_call_heard, motion_issues, caption_issues, endcard_issues, delivery_assessment. Give timecodes for any actual issue and quote audible words rather than guessing. Check that Dynamix is DYE-NAHH-MIX, with broad AH as in father in the middle and short I in mix at the end. Check narration completeness and smooth splice, music ducking, no unexpected singing or extra narration. All four upgraded crew portraits must appear during the bring-every-station-to-life line and each must have its own matching voice bark afterward. Expected barks: {json.dumps(crew)}. Verify actual game logo on cinematic opening and moving tank shot; Genesis-to-Modern colonel comparison; matched side-by-side Original PC versus Modern M1A1, Hind, Sagger and base model studies. Models are native offline studies of real assets, cinematic tank shots are illustrations, other game views are genuine source-packet recordings. Check readable captions, complete 4:3 game display, transitions, flicker/anatomy, experimental Modern qualification, URL, original-PC-game requirement and David Ming Kenny dedication. Separate uncertainties from observed defects; do not invent rights or loudness measurements. Approved narration: '''+script
        prompt+='\nReturn one JSON object, never an array. Include revision_checks as an object with keys logo, colonel, avatars_station_line, four_barks, unit_pairs, requirement_and_dedication. Each value must contain observed visual or audible detail and a timecode, including positive findings. Quote all four barks in four_barks. Inspect the final music-only ending for any actually audible extra words; distinguish silence/instrumental music from ASR hallucinations.'
    if brief.get('revision')=='v3':
        prompt=f'''Review this actual60-second v3 promo, AUDIO and MOTION. It was authored by the requesting assistant in this session. Return one concise JSON object with audio_accessible, video_accessible, verdict(pass or repair), narration_issues, crew_call_heard, motion_issues, caption_issues, endcard_issues, delivery_assessment, revision_checks. Each issue needs a timecode and direct audible/visible evidence. Dynamics must be spoken as the ordinary English word, with a smooth continuous sentence, then was a revolution for its time and Now it's back. Four upgraded avatars must appear during bring every station to life, about21seconds. Each portrait must visibly sweep into its own bark between23 and31seconds. Quote all four actually heard barks; evaluate voice inflection and urgency, rather than assuming dramatic words mean dynamic performance. Expected sources: {json.dumps(brief['crew_showcase'])}. Original PC gameplay appears only5.2 to6.7seconds; thereafter actual gameplay is mode-locked Modern. The Genesis-to-Modern colonel still comparison and Original/Modern unit-pair studies are deliberate comparisons, not gameplay mode flicker. Check for ANY observed fallback, blank, flashing, clipping or jarring motion in game footage. No smoke scene. Modern graphics are experimental, labelled once in model studies. Actual logo appears on cinema shots and endcard. M1A1 tank, Hind helicopter, Sagger team and base must appear side by side with originals. Save states and fast-forward must be mentioned and shown;2x4x8x typography lists real features, background is normal-speed genuine gameplay, not an invented interaction. Endcard must read Fan Remastered by Nell Watson, plus projectURL, original-PC-game requirement and David Ming Kenny memorial. Cinema exteriors are reference-guided illustrations, not gameplay. Check intelligible fresh narration, music balance, readable captions below complete4:3 screen, no extra singing/speech. Do not invent source rights, human listening or measured loudness. revision_checks must have keys dynamics, revolution_return, animated_four_barks, modern_only_gameplay, no_smoke, fast_forward, nell_credit, logo_colonel_unit_pairs, requirement_and_dedication. Give observed evidence and timecodes for positive findings too. Approved narration: '''+script
    if brief.get('revision')=='v4':
        prompt=f'''Review this actual60-second V4 Abrams promo, including its AUDIO and MOTION. The requesting assistant authored it in this session. Return one concise JSON object with audio_accessible, video_accessible, verdict(pass or repair), narration_issues, crew_call_heard, motion_issues, caption_issues, endcard_issues, delivery_assessment, revision_checks. Quote actual audible words and give timecodes. Check these specific revisions: box-art cream-letter logo, not silver game logo, on exterior shots near3 and53seconds; a continuous original-to-Modern wipe during Now it's back around6.7seconds, followed by consistent Modern gameplay; Genesis-to-Modern colonel wipe retained; no Drop back through the hatch narration or hatch shot; all upgraded avatars visible for bring every station to life; slightly brisker four portrait sweeps and matching intelligible barks around22-29seconds; driver ENGINE is overheating must be clear, urgent and insistent, not a flat routine report; direct driver-to-model-showcase cut with NO stray gameplay flash around29-31seconds; four actual Original/Modern unit studies M1A1, Hind, Sagger, base; save states plus Fast-forward functions keep you engaged through the quiet parts spoken and aligned to fast-forward graphic; single logo on endcard, residing in cover art only, no duplicate right-hand logo; Fan Remastered by Nell Watson credit, original-PC-game requirement, projectURL and David Ming Kenny memorial. Dynamics is spoken as ordinary English, captions retain proper Dynamix spelling. Keep complete4:3 gameplay display and readable captions. Cinema is approved illustrative footage; comparisons are deliberate static art, not gameplay mode flicker. Detect actual blanks, flashes, clipped or overlapping speech, offsync captions, anatomy or motion faults. No smoke. Do not infer mathematical loudness, rights or human approval. revision_checks keys: box_logos, return_wipe, no_hatch, brisk_four_barks, urgent_driver, direct_models_cut, fast_forward_line, single_end_logo, retained_content. Positive findings must name actual visible/audible details and timecodes. Expected crew words: {json.dumps(brief['crew_showcase'])}. Approved narration: '''+script
    if brief.get('revision')=='v5':
        prompt=f'''Review this actual60-second V5 Abrams promo including AUDIO and MOTION. The requesting assistant authored it in this session. Return one concise JSONobject with audio_accessible,video_accessible,verdict(pass or repair),narration_issues,crew_call_heard,motion_issues,caption_issues,endcard_issues,delivery_assessment,revision_checks. Quote audible words and timecodes. Specific revisions: cinematic Abrams video must start immediately on One tank,your command near1.03seconds, no early gameplay insert; every cinematic logo has only FAN REMASTER centered underneath, no FREE AND OPEN or Original PC game required text on those scenes; original-game requirement remains on final endcard. During when the shells start landing around10-12seconds, show close actual enemy armour in magnified Modern gunner view and a clearly audible Engine damaged warning, then resume narration smoothly. After bring every station to life around21.6seconds, commander bark must begin immediately, followed by4brisk portrait sweeps and4matching intelligible calls. Detect any awkward dead air there. Preserve urgent Engine is overheating driver retake. Leave a perceptible extra1-second musical beat before The remaster is free and open near47.55seconds, no clipped sentence boundary. Retain all prior edits: ordinary spoken Dynamics/proper captionDynamix,5.2-6.7original insert and original→Modernwipe,Genesis→Moderncolonel,complete4:3 gameplay,avatars forstationline,Original/ModernM1A1,Hind,Sagger,base,savestates andFast-forward functions keep you engaged through the quiet parts,no smoke/hatch/straygameplayflash beforemodels,singleendcardcoverlogo,NellWatsoncredit,projectURL,originalPCrequirement,DavidMingKennymemorial. Cinema is illustrative footage; enemycombat is genuine ordinary-input source replay with1x3x10x optical magnification through actual Modern renderer. Engine damaged is an editorial use of the actual installed warning bank; do not assume this source event occurred in the capture. Inspect blanks,flicker,anatomy,captionclipping,overlapping/truncated speech,musicbalance or unexpected singing. Never infer rights, mathematical measurements or humanapproval. revision_checks keys: immediate_cinema,clean_centered_logo_tags,close_enemy_damage_bark,immediate_four_barks,free_open_extra_beat,retained_edits. Positive findings need observed details andtimecodes. Expected fourbarks: {json.dumps(brief['crew_showcase'])}. Approved narrator speech: '''+script
    budget(out,a.action,.5)
    proxy_sha=hashlib.sha256(proxy.read_bytes()).hexdigest()
    payload={'model':a.model,'messages':[{'role':'user','content':[{'type':'text','text':prompt},{'type':'video_url','video_url':{'url':'data:video/mp4;base64,'+base64.b64encode(proxy.read_bytes()).decode()},'processing':'static'}]}],'max_tokens':10000,'response_format':{'type':'json_object'},'temperature':.1}
    if a.reasoning_effort:payload['reasoning']={'effort':a.reasoning_effort}
    response=request('POST','/chat/completions',json=payload).json()
    review=response['choices'][0]['message']['content']
    receipt(out,a.action,{'model':a.model,'reasoning_effort':a.reasoning_effort,'video_sha256':video_sha,'proxy_sha256':proxy_sha,'finish_reason':response['choices'][0].get('finish_reason'),'review':review,'usage':response.get('usage')})
    assert hashlib.sha256(video.read_bytes()).hexdigest()==video_sha,'Reviewed source changed while review was in flight'
    assert response['choices'][0].get('finish_reason')=='stop','Truncated audiovisual review is not acceptance evidence'
    parsed=json.loads(review)
    if isinstance(parsed,list) and len(parsed)==1:parsed=parsed[0]
    assert parsed['audio_accessible'] and parsed['video_accessible'],'Critic did not access actual audiovisual input'
    for field in ['narration_issues','crew_call_heard','motion_issues','caption_issues','endcard_issues','delivery_assessment']:assert field in parsed,field
    if brief.get('revision')=='v2':
        for field in ['logo','colonel','avatars_station_line','four_barks','unit_pairs','requirement_and_dedication']:assert parsed['revision_checks'].get(field),field
    if brief.get('revision')=='v3':
        for field in ['dynamics','revolution_return','animated_four_barks','modern_only_gameplay','no_smoke','fast_forward','nell_credit','logo_colonel_unit_pairs','requirement_and_dedication']:assert parsed['revision_checks'].get(field),field
    if brief.get('revision')=='v4':
        for field in ['box_logos','return_wipe','no_hatch','brisk_four_barks','urgent_driver','direct_models_cut','fast_forward_line','single_end_logo','retained_content']:assert parsed['revision_checks'].get(field),field
    if brief.get('revision')=='v5':
        for field in ['immediate_cinema','clean_centered_logo_tags','close_enemy_damage_bark','immediate_four_barks','free_open_extra_beat','retained_edits']:assert parsed['revision_checks'].get(field),field
    print(review)

if __name__=='__main__':main()
